spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.45.64:8849
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
  session:
    store-type: redis
server:
  port: 12000
logging:
  level:
    com.zsy: debug
